# HIL: SAADC internal VDD (CR2032 / direct supply). No FUEL divider on Tag.
CONFIG_GPIO=y
CONFIG_ADC=y

CONFIG_BT=y
CONFIG_BT_BROADCASTER=y
CONFIG_BT_DEVICE_NAME="JX_VDD"

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_MAIN_STACK_SIZE=4096
